version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: budget_mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: budget-manager
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - budget_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # UI Service - Development Mode
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
      args:
        VITE_API_URL: /api
    container_name: budget_ui_dev
    restart: unless-stopped
    volumes:
      # Mount source code for hot reload
      - ./ui/src:/app/src:ro
      - ./ui/public:/app/public:ro
      - ./ui/index.html:/app/index.html:ro
      - ./ui/package.json:/app/package.json:ro
      - ./ui/vite.config.js:/app/vite.config.js:ro
      - ./ui/tailwind.config.js:/app/tailwind.config.js:ro
      - ./ui/postcss.config.mjs:/app/postcss.config.mjs:ro
    ports:
      - "5173:5173"  # Expose Vite dev server
    environment:
      - NODE_ENV=development
    networks:
      - budget_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Service - Development Mode  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: budget_api_dev
    restart: unless-stopped
    volumes:
      # Mount source code for nodemon
      - ./api/src:/app/src:ro
      - ./api/package.json:/app/package.json:ro
      - ./api/start-dev.sh:/app/start-dev.sh:ro
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/budget-manager?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - budget_network

  # Nginx - Development configuration
  nginx:
    image: nginx:alpine
    container_name: budget_nginx_dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ui
    networks:
      - budget_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data:
    driver: local

networks:
  budget_network:
    driver: bridge